services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:password@db:5432/fuellife
  #   depends_on:
  #     - postgresql
  #   command: sh -c "npm run build && npm run start"

  postgresql:
    container_name: postgresql
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fuellife
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: